# Kernel-specific configurations for different experiments
# These can be used to test different kernel functions
# NOTE: LinearKernel causes numerical instability (rank deficit, Lyapunov solver issues)
# Use only RBF kernels for stable computation

kernels:
  # RBF (Gaussian) Kernel: K(x, y) = exp(-||x-y||^2 / (2*sigma^2))
  rbf_small:
    type: "rbf"
    sigma: 0.5
    description: "RBF kernel with small bandwidth"
    
  rbf_medium:
    type: "rbf"
    sigma: 1.0
    description: "RBF kernel with medium bandwidth (default, most stable)"
    
  rbf_large:
    type: "rbf"
    sigma: 2.0
    description: "RBF kernel with large bandwidth"
  
  rbf_extra_large:
    type: "rbf"
    sigma: 3.0
    description: "RBF kernel with extra large bandwidth"

# Default kernel for experiments (most stable)
default: "rbf_medium"

# Kernel combinations for comparative analysis
comparisons:
  bandwidth_study:
    - "rbf_small"
    - "rbf_medium"
    - "rbf_large"
    - "rbf_extra_large"
    
  stable_kernels:
    - "rbf_small"
    - "rbf_medium"
    - "rbf_large"
